###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2021. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
---
#Create secret for IBM Cloud Pak for Automation shared encryptionKey
apiVersion: v1
kind: Secret
metadata:
  name: icp4a-shared-key-secret
type: Opaque
stringData:
  encryptionKey: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: icp4a-shared-encryption-key
type: Opaque
stringData:
  encryptionKey: Welcome123
---
#Create secret for Business Automation Workflow database credential
apiVersion: v1
kind: Secret
metadata:
  name: ibm-baw-db-secret-postgresql
type: Opaque
stringData:
  dbUser: "postgres"
  password: "Welcome123"

---
#Create secret for User Management Service
apiVersion: v1
kind: Secret
metadata:
  name: ibm-dba-ums-secret
type: Opaque
stringData:
  adminUser: "cp4badmin"
  adminPassword: "passw0rd"
  sslKeystorePassword: "sslPassword"
  jwtKeystorePassword: "jwtPassword"
  teamserverClientID: "ts"
  teamserverClientSecret: "tsSecret"
  ltpaPassword: "ltpaPassword"
  oauthDBUser: "postgres"
  oauthDBPassword: "Welcome123"
  tsDBUser: "postgres"
  tsDBPassword: "Welcome123"
  tosDBUsername: "postgres"
  tosDBPassword: "Welcome123" 
  dosDBUsername: "postgres"
  dosDBPassword: "Welcome123" 
  docsDBUsername: "postgres"
  docsDBPassword: "Welcome123" 
  aeosDBUsername: "postgres"
  aeosDBPassword: "Welcome123" 
---
# Source: helper/templates/base/fncm-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: ibm-fncm-secret
type: Opaque
stringData:
  gcdDBUsername: "postgres"
  gcdDBPassword: "Welcome123"
  osDBUsername: "postgres"
  osDBPassword: "Welcome123"
  ltpaPassword: "Welcome123"
  ldapUsername: "cn=root"
  ldapPassword: "Welcome123"
  keystorePassword: ""
  navigatorDBUsername: "postgres"
  navigatorDBPassword: "Welcome123"
  appLoginUsername: "cp4badmin"
  appLoginPassword: "passw0rd"
  tosDBUsername: "postgres"
  tosDBPassword: "Welcome123" 
  dosDBUsername: "postgres"
  dosDBPassword: "Welcome123" 
  docsDBUsername: "postgres"
  docsDBPassword: "Welcome123" 
  aeosDBUsername: "postgres"
  aeosDBPassword: "Welcome123"   
---
# Source: helper/templates/base/navigatorSecret.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: ibm-ban-secret
type: Opaque
stringData:
  navigatorDBUsername: "Welcome123"
  navigatorDBPassword: "postgres"
  ldapUsername: "cn=root"
  ldapPassword: "Welcome123"
  appLoginUsername: "cp4badmin"
  appLoginPassword: "passw0rd"
  ltpaPassword: ""
  keystorePassword: ""

---
apiVersion: v1
kind: Secret
metadata:
  name: ibm-ae-admin-secret
type: Opaque
stringData:
  ADMIN_USER: "cp4badmin"
  AE_DATABASE_PWD: "Welcome123"
  AE_DATABASE_USER: "postgres"
  OPENID_CLIENT_ID: "app_engine"
  OPENID_CLIENT_SECRET: ""
  SESSION_SECRET: "bigblue123solutionserver"
  SESSION_COOKIE_NAME: "nsessionid"
  REDIS_PASSWORD: "password"
---
apiVersion: v1
stringData:
  AE_DATABASE_PWD: "Welcome123"
  AE_DATABASE_USER: "postgres"
  REDIS_PASSWORD: "password"
kind: Secret
metadata:
  name: icp4adeploy-workspace-aae-app-engine-admin-secret
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: ibm-baw-wfs-server-db-secret
type: Opaque
stringData:
  dbUser: "postgres"
  password: "Welcome123"
---
apiVersion: v1
kind: Secret
metadata:
 name: ibm-baw-wc-secret
type: Opaque
stringData:
 username: deadmin
 password: deadmin